/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import Model.City;
import Model.Community;
import Model.CommunityDirectory;
import Model.Doctor;
import Model.DoctorDirectory;
import Model.EncounterHistory;
import Model.Hospital;
import Model.HospitalDirectory;
import Model.HouseDirectory;
import Model.PatientDirectory;
import Model.Person;
import Model.PersonDirectory;
import java.util.ArrayList;

/**
 *
 * @author Swapnil
 */
public class MainJFrame extends javax.swing.JFrame {

    PersonDirectory personDirectory;
    PatientDirectory patientDirectory;
    DoctorDirectory doctorDirectory;
    EncounterHistory encounterHistory;
    HospitalDirectory hospitalDirectory;
    ArrayList<City> cityList;
    CommunityDirectory communityDirectory;
    HouseDirectory houseDirectory;
    
    public MainJFrame() {
        initComponents();
        personDirectory = new PersonDirectory();
        patientDirectory = new PatientDirectory();
        doctorDirectory = new DoctorDirectory();
        encounterHistory = new EncounterHistory();
        hospitalDirectory = new HospitalDirectory();
        communityDirectory = new CommunityDirectory();
        cityList = new ArrayList<City>();
        houseDirectory = new HouseDirectory();
        addDoctors(doctorDirectory.getDoctorList());
        addCity(cityList);
        addCommunity(communityDirectory.getCommunityList());
        addHospital(hospitalDirectory.getHospitalList());
        addPerson(personDirectory.getPersonList());
    }
    
     private void addPerson(ArrayList personList){
      Person p1 = new Person("Dushyant", "Mahajan", 25, "Boston", "Allston", "Sector 21", 12345, "dushyant", "Dushyant@123", "Male");
      
      personList.add(p1);
    }
    
    private void addDoctors(ArrayList doctorList){
        Doctor d1 = new Doctor(12345, "Ann", "Anand", 63, "Mass Hospital", 12345, "Ann63", "pass123");
        Doctor d2 = new Doctor(23456, "Carl", "Ugi", 56, "Mass Hospital", 12345, "Ugi156", "pass234");
        Doctor d3 = new Doctor(34567, "Fran", "Hawkins", 33, "Arbour Hospital", 23456, "Hawkins33", "pass345");
        Doctor d4 = new Doctor(45678, "Lenny", "Chan", 24, "Arbour Hospital", 23456, "chan24", "pass456");
        
        doctorList.add(d1);
        doctorList.add(d2);
        doctorList.add(d3);
        doctorList.add(d4);
    }

    private void addCity(ArrayList cityList){
        City c1 = new City("Boston", 12345);
        City c2 = new City("New York", 23456);
        
        cityList.add(c1);
        cityList.add(c2);
    }
    
    private void addCommunity(ArrayList communityList){
        Community c1 = new Community("Allston",12345,12345);
        Community c2 = new Community("Charlstown", 23456, 12345);
        
        communityList.add(c1);
        communityList.add(c2);
    }
    
    private void addHospital(ArrayList hospitalList){
        Hospital h1 = new Hospital(12345, "Mass Hospital", 100, 12345, "Allston", "Boston");
        Hospital h2 = new Hospital(23456, "Boston Hospital", 120, 23456, "Charlestown", "Boston");
       
        hospitalList.add(h1);
        hospitalList.add(h2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPanel = new javax.swing.JSplitPane();
        userPanel = new javax.swing.JPanel();
        systemAdminBtn = new javax.swing.JButton();
        communityAdminBtn = new javax.swing.JButton();
        doctorBtn = new javax.swing.JButton();
        personBtn = new javax.swing.JButton();
        hospitalAdminBtn = new javax.swing.JButton();
        workAreaPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));

        splitPanel.setBackground(new java.awt.Color(153, 204, 255));

        userPanel.setBackground(new java.awt.Color(255, 255, 255));
        userPanel.setPreferredSize(new java.awt.Dimension(200, 600));

        systemAdminBtn.setBackground(new java.awt.Color(102, 204, 255));
        systemAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        systemAdminBtn.setText("System Admin");
        systemAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemAdminBtnActionPerformed(evt);
            }
        });

        communityAdminBtn.setBackground(new java.awt.Color(102, 204, 255));
        communityAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        communityAdminBtn.setText("Community Admin");
        communityAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityAdminBtnActionPerformed(evt);
            }
        });

        doctorBtn.setBackground(new java.awt.Color(102, 204, 255));
        doctorBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        doctorBtn.setText("Doctor");
        doctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorBtnActionPerformed(evt);
            }
        });

        personBtn.setBackground(new java.awt.Color(102, 204, 255));
        personBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personBtn.setText("Person");
        personBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personBtnActionPerformed(evt);
            }
        });

        hospitalAdminBtn.setBackground(new java.awt.Color(102, 204, 255));
        hospitalAdminBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hospitalAdminBtn.setText("Hospital Admin");
        hospitalAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(communityAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(systemAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doctorBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(personBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(hospitalAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(personBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(doctorBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hospitalAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(communityAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(systemAdminBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );

        splitPanel.setLeftComponent(userPanel);

        workAreaPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout workAreaPanelLayout = new javax.swing.GroupLayout(workAreaPanel);
        workAreaPanel.setLayout(workAreaPanelLayout);
        workAreaPanelLayout.setHorizontalGroup(
            workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        workAreaPanelLayout.setVerticalGroup(
            workAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        splitPanel.setRightComponent(workAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void systemAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemAdminBtnActionPerformed
        // TODO add your handling code here:
        viewSystemPanel systemPanel = new viewSystemPanel(personDirectory, patientDirectory, cityList, communityDirectory, houseDirectory, hospitalDirectory, doctorDirectory);
        splitPanel.setRightComponent(systemPanel);
    }//GEN-LAST:event_systemAdminBtnActionPerformed

    private void communityAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityAdminBtnActionPerformed
        // TODO add your handling code here:
        viewCommunityPanel communityPanel = new viewCommunityPanel(hospitalDirectory, houseDirectory, cityList, communityDirectory);
        splitPanel.setRightComponent(communityPanel);
    }//GEN-LAST:event_communityAdminBtnActionPerformed

    private void doctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorBtnActionPerformed
        // TODO add your handling code here:
        viewDoctorPanel doctorPanel = new viewDoctorPanel(encounterHistory, patientDirectory, doctorDirectory);
        splitPanel.setRightComponent(doctorPanel);
    }//GEN-LAST:event_doctorBtnActionPerformed

    private void personBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personBtnActionPerformed
        // TODO add your handling code here:
        viewPersonPanel viewPerson = new viewPersonPanel(personDirectory, patientDirectory, cityList, communityDirectory, hospitalDirectory
            , doctorDirectory, houseDirectory);
        splitPanel.setRightComponent(viewPerson);
    }//GEN-LAST:event_personBtnActionPerformed

    private void hospitalAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalAdminBtnActionPerformed
        // TODO add your handling code here:
        viewHospitalPanel hospitalPanel = new viewHospitalPanel(doctorDirectory, hospitalDirectory);
        splitPanel.setRightComponent(hospitalPanel);
    }//GEN-LAST:event_hospitalAdminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton communityAdminBtn;
    private javax.swing.JButton doctorBtn;
    private javax.swing.JButton hospitalAdminBtn;
    private javax.swing.JButton personBtn;
    private javax.swing.JSplitPane splitPanel;
    private javax.swing.JButton systemAdminBtn;
    private javax.swing.JPanel userPanel;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables
}
