/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author dumma
 */
public class SystemAdminPage extends javax.swing.JFrame {

    /**
     * Creates new form SystemAdminPage
     */
    public SystemAdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitpane = new javax.swing.JSplitPane();
        rightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        closeBtn = new javax.swing.JLabel();
        leftPanel = new javax.swing.JPanel();
        bookAppointmentTxt1 = new javax.swing.JLabel();
        encounterTxt2 = new javax.swing.JLabel();
        encounterTxt3 = new javax.swing.JLabel();
        encounterTxt4 = new javax.swing.JLabel();
        encounterTxt5 = new javax.swing.JLabel();
        encounterTxt6 = new javax.swing.JLabel();
        bookAppointmentTxt2 = new javax.swing.JLabel();
        encounterTxt7 = new javax.swing.JLabel();
        encounterTxt9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitpane.setBackground(new java.awt.Color(255, 255, 255));
        splitpane.setDividerLocation(177);
        splitpane.setPreferredSize(new java.awt.Dimension(870, 540));

        rightPanel.setBackground(new java.awt.Color(179, 229, 252));
        rightPanel.setPreferredSize(new java.awt.Dimension(710, 540));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome System Admin");

        closeBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        closeBtn.setText("x");
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addComponent(closeBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(239, 239, 239))))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(479, Short.MAX_VALUE))
        );

        splitpane.setRightComponent(rightPanel);

        leftPanel.setBackground(new java.awt.Color(129, 211, 250));
        leftPanel.setPreferredSize(new java.awt.Dimension(160, 540));

        bookAppointmentTxt1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookAppointmentTxt1.setText("VIEW");
        bookAppointmentTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookAppointmentTxt1MouseClicked(evt);
            }
        });

        encounterTxt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encounterTxt2.setText("<html> <u>Persons</u> </html>");

        encounterTxt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encounterTxt3.setText("<html>\n<u>Hospitals</u>\n</html>");

        encounterTxt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encounterTxt4.setText("<html> <u>Patients</u> </html>");

        encounterTxt5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encounterTxt5.setText("<html> <u>Doctors</u> </html>");

        encounterTxt6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encounterTxt6.setText("<html> <u>Encounters</u> </html>");

        bookAppointmentTxt2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookAppointmentTxt2.setText("ADMINS");
        bookAppointmentTxt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookAppointmentTxt2MouseClicked(evt);
            }
        });

        encounterTxt7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encounterTxt7.setText("<html> <u>Hospital Admin</u> </html>");

        encounterTxt9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        encounterTxt9.setText("<html> <u>Community Admin</u> </html>");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(bookAppointmentTxt1)
                    .addComponent(encounterTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encounterTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encounterTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encounterTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encounterTxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookAppointmentTxt2)
                    .addComponent(encounterTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encounterTxt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(bookAppointmentTxt1)
                .addGap(18, 18, 18)
                .addComponent(encounterTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(encounterTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(encounterTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(encounterTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(encounterTxt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookAppointmentTxt2)
                .addGap(18, 18, 18)
                .addComponent(encounterTxt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(encounterTxt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        splitpane.setLeftComponent(leftPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitpane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeBtnMouseClicked

    private void bookAppointmentTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookAppointmentTxt1MouseClicked
        //        patientHistory history = null;
        // TODO add your handling code here:
        //        BookAppointmentPanel bookAppointmentpanel = new BookAppointmentPanel(history);
        //        splitpane.setRightComponent(bookAppointmentpanel);
    }//GEN-LAST:event_bookAppointmentTxt1MouseClicked

    private void bookAppointmentTxt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookAppointmentTxt2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bookAppointmentTxt2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemAdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SystemAdminPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookAppointmentTxt1;
    private javax.swing.JLabel bookAppointmentTxt2;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JLabel encounterTxt2;
    private javax.swing.JLabel encounterTxt3;
    private javax.swing.JLabel encounterTxt4;
    private javax.swing.JLabel encounterTxt5;
    private javax.swing.JLabel encounterTxt6;
    private javax.swing.JLabel encounterTxt7;
    private javax.swing.JLabel encounterTxt9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JSplitPane splitpane;
    // End of variables declaration//GEN-END:variables
}
