/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Model.City;
import Model.Community;
import Model.CommunityDirectory;
import Model.Doctor;
import Model.DoctorDirectory;
import Model.Hospital;
import Model.HospitalDirectory;
import Model.House;
import Model.HouseDirectory;
import Model.Patient;
import Model.PatientDirectory;
import Model.Person;
import Model.PersonDirectory;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/**
 *
 * @author Swapnil
 */
public class viewPersonPanel extends javax.swing.JPanel {

    PatientDirectory patientDirectory;
    PersonDirectory personDirectory;
    Person loggedinPerson;
    boolean loggedIn;
    ArrayList<City> cityList;
    CommunityDirectory communityDirectory;
    HospitalDirectory hospitalDirectory;
    DoctorDirectory doctorDirectory;
    HouseDirectory houseDirectory;
    
    public viewPersonPanel(PersonDirectory personDirectory, PatientDirectory patientDirectory, ArrayList<City> cityList, CommunityDirectory communityDirectory, HospitalDirectory hospitalDirectory
    , DoctorDirectory doctorDirectory, HouseDirectory houseDirectory) {
        initComponents();
        this.personDirectory = personDirectory;
        this.patientDirectory = patientDirectory;
        this.communityDirectory = communityDirectory;
        this.cityList = cityList;  
        this.hospitalDirectory = hospitalDirectory;
        this.doctorDirectory = doctorDirectory;
        this.houseDirectory = houseDirectory;
        
        loggedinPerson = new Person();
        loggedIn = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        loginPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtuserName = new javax.swing.JTextField();
        lblUserName1 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        registerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblFname = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        lblLname = new javax.swing.JLabel();
        txtLname = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblComm = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblHouseNo = new javax.swing.JLabel();
        lblHouseNo1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        lblHouseNo2 = new javax.swing.JLabel();
        personRegisterBtn = new javax.swing.JButton();
        backToLoginBtn = new javax.swing.JButton();
        chooseHouseBox = new javax.swing.JComboBox<>();
        lblfname = new javax.swing.JLabel();
        lbllname = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        cityComboBox1 = new javax.swing.JComboBox<>();
        commComboBox1 = new javax.swing.JComboBox<>();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        btnAddNewCity = new javax.swing.JButton();
        btnAddNewComm = new javax.swing.JButton();
        btnAddNewHouse = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblAge1 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        personViewOptionPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        findDocBtn = new javax.swing.JButton();
        encounterDetailsBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        personPanel = new javax.swing.JPanel();
        headingLbl = new javax.swing.JLabel();
        cityLbl = new javax.swing.JLabel();
        cityComboBox = new javax.swing.JComboBox<>();
        commLbl = new javax.swing.JLabel();
        commComboBox = new javax.swing.JComboBox<>();
        hosLbl = new javax.swing.JLabel();
        hosComboBox = new javax.swing.JComboBox<>();
        docLbl = new javax.swing.JLabel();
        docComboBox = new javax.swing.JComboBox<>();
        bookBtn = new javax.swing.JButton();
        personIdLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        lblPersonId = new javax.swing.JLabel();
        viewEncounterPanel = new javax.swing.JPanel();
        headingLbl1 = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        appointmentTable = new javax.swing.JTable();
        headingLbl2 = new javax.swing.JLabel();
        headingLbl3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        encounterTable = new javax.swing.JTable();

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Person Login");

        lblUserName.setText("Username:");

        lblUserName1.setText("Password:");

        loginBtn.setBackground(new java.awt.Color(255, 153, 153));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        registerBtn.setBackground(new java.awt.Color(102, 255, 102));
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(lblUserName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtuserName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(lblUserName1)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(registerBtn)
                                    .addComponent(loginBtn)))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)))
                .addContainerGap(346, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtuserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName1)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(loginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerBtn)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jLayeredPane1.add(loginPanel, "card2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Person Register");

        lblFname.setFont(new java.awt.Font("Didot", 1, 14)); // NOI18N
        lblFname.setText("First Name:");

        txtFname.setFont(new java.awt.Font("Didot", 3, 14)); // NOI18N
        txtFname.setForeground(new java.awt.Color(153, 153, 0));
        txtFname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFnameKeyReleased(evt);
            }
        });

        lblLname.setFont(new java.awt.Font("Didot", 1, 14)); // NOI18N
        lblLname.setText("Last Name:");

        txtLname.setFont(new java.awt.Font("Didot", 3, 14)); // NOI18N
        txtLname.setForeground(new java.awt.Color(153, 153, 0));
        txtLname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLnameKeyReleased(evt);
            }
        });

        lblAge.setFont(new java.awt.Font("Didot", 1, 14)); // NOI18N
        lblAge.setText("Age:");

        txtAge.setFont(new java.awt.Font("Didot", 3, 14)); // NOI18N
        txtAge.setForeground(new java.awt.Color(153, 153, 0));
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });

        lblComm.setFont(new java.awt.Font("Didot", 1, 14)); // NOI18N
        lblComm.setText("Community:");

        lblCity.setFont(new java.awt.Font("Didot", 1, 14)); // NOI18N
        lblCity.setText("City:");

        lblHouseNo.setFont(new java.awt.Font("Didot", 1, 14)); // NOI18N
        lblHouseNo.setText("House Number:");

        lblHouseNo1.setFont(new java.awt.Font("Didot", 1, 14)); // NOI18N
        lblHouseNo1.setText("Username:");

        txtUserName.setFont(new java.awt.Font("Didot", 3, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(153, 153, 0));
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserNameKeyReleased(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Didot", 3, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(153, 153, 0));
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });

        lblHouseNo2.setFont(new java.awt.Font("Didot", 1, 14)); // NOI18N
        lblHouseNo2.setText("Password:");

        personRegisterBtn.setBackground(new java.awt.Color(102, 255, 102));
        personRegisterBtn.setText("Register");
        personRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personRegisterBtnActionPerformed(evt);
            }
        });

        backToLoginBtn.setText("Back");
        backToLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToLoginBtnActionPerformed(evt);
            }
        });

        chooseHouseBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));

        lblfname.setFont(new java.awt.Font("Didot", 3, 14)); // NOI18N
        lblfname.setForeground(new java.awt.Color(0, 102, 102));

        lbllname.setFont(new java.awt.Font("Didot", 3, 14)); // NOI18N
        lbllname.setForeground(new java.awt.Color(0, 102, 102));

        lblage.setFont(new java.awt.Font("Didot", 3, 14)); // NOI18N
        lblage.setForeground(new java.awt.Color(0, 102, 102));
        lblage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblageKeyReleased(evt);
            }
        });

        cityComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "New York" }));
        cityComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityComboBox1ActionPerformed(evt);
            }
        });

        commComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        commComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commComboBox1ActionPerformed(evt);
            }
        });

        lblusername.setFont(new java.awt.Font("Didot", 3, 14)); // NOI18N
        lblusername.setForeground(new java.awt.Color(0, 102, 102));

        lblpassword.setFont(new java.awt.Font("Didot", 3, 14)); // NOI18N
        lblpassword.setForeground(new java.awt.Color(0, 102, 102));

        btnAddNewCity.setText("Add New City");
        btnAddNewCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCityActionPerformed(evt);
            }
        });

        btnAddNewComm.setText("Add New Community");
        btnAddNewComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCommActionPerformed(evt);
            }
        });

        btnAddNewHouse.setText("Add New House");
        btnAddNewHouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewHouseActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblAge1.setFont(new java.awt.Font("Didot", 1, 14)); // NOI18N
        lblAge1.setText("Gender:");

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Other" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(backToLoginBtn)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addGap(74, 74, 74))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerPanelLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(registerPanelLayout.createSequentialGroup()
                                        .addComponent(lblAge)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(registerPanelLayout.createSequentialGroup()
                                        .addComponent(lblLname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(registerPanelLayout.createSequentialGroup()
                                        .addComponent(lblFname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(registerPanelLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(registerPanelLayout.createSequentialGroup()
                                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(chooseHouseBox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, registerPanelLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblComm)
                                                    .addComponent(lblCity)
                                                    .addComponent(lblAge1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(cityComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(commComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(genderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnAddNewCity)
                                            .addComponent(btnAddNewComm)
                                            .addComponent(btnAddNewHouse)))
                                    .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(registerPanelLayout.createSequentialGroup()
                                            .addComponent(lblHouseNo)
                                            .addGap(145, 145, 145))
                                        .addGroup(registerPanelLayout.createSequentialGroup()
                                            .addComponent(lblHouseNo1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(registerPanelLayout.createSequentialGroup()
                                            .addComponent(lblHouseNo2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(registerPanelLayout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(personRegisterBtn)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblfname, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(lbllname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblusername, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(lblpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                .addContainerGap())
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(backToLoginBtn)))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnRefresh)))
                .addGap(29, 29, 29)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFname)
                                .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblfname, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLname)
                            .addComponent(txtLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbllname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAge)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblage, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge1)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCity)
                            .addComponent(btnAddNewCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(commComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComm)
                            .addComponent(btnAddNewComm))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHouseNo)
                            .addComponent(chooseHouseBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddNewHouse))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHouseNo1)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHouseNo2)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(personRegisterBtn)))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jLayeredPane1.add(registerPanel, "card3");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Welcome");

        findDocBtn.setBackground(new java.awt.Color(204, 255, 204));
        findDocBtn.setText("Find A Doctor");
        findDocBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findDocBtnActionPerformed(evt);
            }
        });

        encounterDetailsBtn.setBackground(new java.awt.Color(0, 204, 255));
        encounterDetailsBtn.setText("View Encounter Details");
        encounterDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterDetailsBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(255, 255, 204));
        logoutBtn.setText("Logout");
        logoutBtn.setToolTipText("");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personViewOptionPanelLayout = new javax.swing.GroupLayout(personViewOptionPanel);
        personViewOptionPanel.setLayout(personViewOptionPanelLayout);
        personViewOptionPanelLayout.setHorizontalGroup(
            personViewOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personViewOptionPanelLayout.createSequentialGroup()
                .addGroup(personViewOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personViewOptionPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(logoutBtn))
                    .addGroup(personViewOptionPanelLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addGroup(personViewOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(findDocBtn)))
                    .addGroup(personViewOptionPanelLayout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(encounterDetailsBtn)))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        personViewOptionPanelLayout.setVerticalGroup(
            personViewOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personViewOptionPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(logoutBtn)
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addComponent(findDocBtn)
                .addGap(28, 28, 28)
                .addComponent(encounterDetailsBtn)
                .addContainerGap(257, Short.MAX_VALUE))
        );

        jLayeredPane1.add(personViewOptionPanel, "card2");

        headingLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headingLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLbl.setText("Find a Doctor");

        cityLbl.setText("Select City:");

        cityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "New York" }));
        cityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityComboBoxActionPerformed(evt);
            }
        });

        commLbl.setText("Select Community:");

        commComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        commComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commComboBoxActionPerformed(evt);
            }
        });

        hosLbl.setText("Select Hospital:");

        hosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        hosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosComboBoxActionPerformed(evt);
            }
        });

        docLbl.setText("Select Doctor:");

        docComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        docComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docComboBoxActionPerformed(evt);
            }
        });

        bookBtn.setBackground(new java.awt.Color(153, 153, 255));
        bookBtn.setText("Book Appointment");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        personIdLbl.setText("PersonID:");

        backBtn.setText("back");
        backBtn.setToolTipText("");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personPanelLayout = new javax.swing.GroupLayout(personPanel);
        personPanel.setLayout(personPanelLayout);
        personPanelLayout.setHorizontalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(personPanelLayout.createSequentialGroup()
                                    .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cityLbl)
                                        .addComponent(commLbl)
                                        .addComponent(personIdLbl))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(commComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cityComboBox, 0, 153, Short.MAX_VALUE)
                                        .addComponent(lblPersonId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(personPanelLayout.createSequentialGroup()
                                    .addComponent(hosLbl)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(docLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookBtn)
                                    .addComponent(docComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(personPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(backBtn)
                        .addGap(54, 54, 54)
                        .addComponent(headingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        personPanelLayout.setVerticalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addGap(36, 36, 36)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(personIdLbl)
                    .addComponent(lblPersonId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hosLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(docComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(bookBtn)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        jLayeredPane1.add(personPanel, "card4");

        headingLbl1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        headingLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLbl1.setText("View Encounters");

        backBtn1.setText("back");
        backBtn1.setToolTipText("");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        appointmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Doctor Name", "Hospital Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appointmentTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                appointmentTableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(appointmentTable);

        headingLbl2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        headingLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLbl2.setText("Appointment Details");

        headingLbl3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        headingLbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingLbl3.setText("Encounter Details");

        encounterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Timestamp", "Temperature", "Blood Pressure", "Pulse", "Doctor Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(encounterTable);

        javax.swing.GroupLayout viewEncounterPanelLayout = new javax.swing.GroupLayout(viewEncounterPanel);
        viewEncounterPanel.setLayout(viewEncounterPanelLayout);
        viewEncounterPanelLayout.setHorizontalGroup(
            viewEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewEncounterPanelLayout.createSequentialGroup()
                .addGroup(viewEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(viewEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(viewEncounterPanelLayout.createSequentialGroup()
                            .addGap(268, 268, 268)
                            .addComponent(headingLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(viewEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(viewEncounterPanelLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(viewEncounterPanelLayout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(backBtn1)
                            .addGap(152, 152, 152)
                            .addGroup(viewEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(viewEncounterPanelLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(headingLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(headingLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewEncounterPanelLayout.setVerticalGroup(
            viewEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewEncounterPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(viewEncounterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn1)
                    .addComponent(headingLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(headingLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(headingLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(viewEncounterPanel, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String userName = txtuserName.getText();
        String password = txtPassword.getText();

        for(Person p: personDirectory.getPersonList()){
            String uN = p.getPersonUserName();
            String pW = p.getPersonPassword();

            if(uN.equals(userName) && pW.equals(password)){
                loggedinPerson = p;
                loggedIn = true;
                System.out.println("login successful");
                break;
            }
        }

        if(loggedIn == true){
            switchPanels(personViewOptionPanel);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        switchPanels(registerPanel);

    }//GEN-LAST:event_registerBtnActionPerformed

    private void txtFnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,50}";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtFname.getText());
        if(!match.matches()){
            lblfname.setText("Name is Invalid, Please enter Valid name !");
        }else{
            lblfname.setText("");
        }
    }//GEN-LAST:event_txtFnameKeyReleased

    private void txtLnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{0,50}";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtLname.getText());
        if(!match.matches()){
            lbllname.setText("Name is Invalid, Please enter Valid name !");
        }else{
            lbllname.setText("");
        }
    }//GEN-LAST:event_txtLnameKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,3}";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtAge.getText());
        if(!match.matches()){
            lblage.setText("Only Numbers and upto 3 digits are allowed");
        }else{
            lblage.setText("");
        }
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyReleased
        // TODO add your handling code here:
        String username = txtUserName.getText();
        for(Person p: personDirectory.getPersonList()){
            if(username.equals(p.getPersonUserName())){
                lblusername.setText("Username already exists. Pick a new one.");
            }
            else{
                lblusername.setText("");
            }
        }
    }//GEN-LAST:event_txtUserNameKeyReleased

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#&()–[{}]:;',?/*~$^+=<>]).{8,20}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txtPass.getText());
        if(!match.matches()){
            lblpassword.setText("<html>Not a valid password. Password must contain at least one digit [0-9]<br/>"
                + "Password must contain at least one lowercase character [a-z] <br/>"
                + "Password must contain at least one uppercase character [A-Z] <br/>"
                + "Password must contain at least one special character like ! @ # & ( )<br/>"
                + "Password must contain a length of at least 8 characters and a maximum of 20 characters</html>"
            );
        }else{
            lblpassword.setText("");
        }
    }//GEN-LAST:event_txtPassKeyReleased

    private void personRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personRegisterBtnActionPerformed
        if(txtAge.getText()== null || txtAge.getText().isEmpty()
            || txtUserName.getText()== null || txtUserName.getText().isEmpty()
            || txtFname.getText()== null || txtFname.getText().isEmpty()
            || txtLname.getText()== null || txtLname.getText().isEmpty()
            || txtPass.getText()== null || txtPass.getText().isEmpty()
        ){
            JOptionPane.showMessageDialog(this, "Please enter all fields ! ");

        }
        else if(userNameUnique(txtUserName.getText()) == false){
            JOptionPane.showMessageDialog(this, "This username already exists. Please choose a unique username! ");
        }
        else{
            Person person = new Person();
            person.setPersonAge(Integer.parseInt(txtAge.getText()));
            person.setPersonCityName((String) cityComboBox1.getSelectedItem());
            person.setPersonCommunityName((String) commComboBox1.getSelectedItem());
            person.setPersonHouseNo((String) chooseHouseBox.getSelectedItem());

            person.setFirstName(txtFname.getText());
            person.setLastName(txtLname.getText());
            person.setPersonId(getUniqueId());
            person.setPersonPassword(txtPass.getText());
            person.setPersonUserName(txtUserName.getText());
            person.setGender((String) genderComboBox.getSelectedItem());
            this.personDirectory.addNewPerson(person);
            JOptionPane.showMessageDialog(this, "You have been registered.");
            System.out.println("the person has been added");

            txtFname.setText("");
            txtLname.setText("");
            txtAge.setText("");
            txtUserName.setText("");
            txtPass.setText("");
        }

        /* try {
            // TODO add your handling code here:
            setData();
        } catch (IOException ex) {
            Logger.getLogger(viewPersonPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_personRegisterBtnActionPerformed

    private void backToLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToLoginBtnActionPerformed
        // TODO add your handling code here:
        switchPanels(loginPanel);
    }//GEN-LAST:event_backToLoginBtnActionPerformed

    private void lblageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblageKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblageKeyReleased

    private void cityComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityComboBox1ActionPerformed
        // TODO add your handling code here:

        String cityName = (String) cityComboBox1.getSelectedItem();

        DefaultComboBoxModel bosModel = new DefaultComboBoxModel(requiredCommunity(cityName));
        commComboBox1.setModel(bosModel);

    }//GEN-LAST:event_cityComboBox1ActionPerformed

    private void commComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commComboBox1ActionPerformed
        // TODO add your handling code here:
        String communityName = (String) commComboBox1.getSelectedItem();

        DefaultComboBoxModel hosModel = new DefaultComboBoxModel(requiredHouse(communityName));
        chooseHouseBox.setModel(hosModel);
    }//GEN-LAST:event_commComboBox1ActionPerformed

    private void btnAddNewCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCityActionPerformed
        // TODO add your handling code here:
        addCityFrame addCity = new addCityFrame(cityList);
        addCity.setVisible(true);

    }//GEN-LAST:event_btnAddNewCityActionPerformed

    private void btnAddNewCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCommActionPerformed
        // TODO add your handling code here:
        AddCommunity addCommunity = new AddCommunity(cityList, communityDirectory);
        addCommunity.setVisible(true);
    }//GEN-LAST:event_btnAddNewCommActionPerformed

    private void btnAddNewHouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewHouseActionPerformed
        // TODO add your handling code here:
        AddHouseFrame addHouse = new AddHouseFrame(cityList, communityDirectory, houseDirectory);
        addHouse.setVisible(true);
    }//GEN-LAST:event_btnAddNewHouseActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        DefaultComboBoxModel cityModel = new DefaultComboBoxModel(requiredCity());
        cityComboBox1.setModel(cityModel);

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void findDocBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findDocBtnActionPerformed
        // TODO add your handling code here:
        switchPanels(personPanel);
    }//GEN-LAST:event_findDocBtnActionPerformed

    private void encounterDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterDetailsBtnActionPerformed
        // TODO add your handling code here:
        switchPanels(viewEncounterPanel);
    }//GEN-LAST:event_encounterDetailsBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        switchPanels(loginPanel);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void cityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityComboBoxActionPerformed
        // TODO add your handling code here:

        String cityName = (String) cityComboBox.getSelectedItem();

        DefaultComboBoxModel bosModel = new DefaultComboBoxModel(requiredCommunity(cityName));
        commComboBox.setModel(bosModel);

        /*  if ("Boston".equals(cityComboBox.getSelectedItem())){
            //DefaultComboBoxModel bosModel = new DefaultComboBoxModel(new String[]{"Allston", "Charlestown"});
            DefaultComboBoxModel bosModel = new DefaultComboBoxModel(requiredCommunity("Boston"));
            commComboBox.setModel(bosModel);
        } else {
            commComboBox.setModel(nyModel);
        }*/
    }//GEN-LAST:event_cityComboBoxActionPerformed

    private void commComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commComboBoxActionPerformed
        // TODO add your handling code here:
        String communityName = (String) commComboBox.getSelectedItem();

        DefaultComboBoxModel hosModel = new DefaultComboBoxModel(requiredHospital(communityName));
        hosComboBox.setModel(hosModel);

        /* if ("Allston".equals(commComboBox.getSelectedItem())){
            hosComboBox.setModel(allModel);
        } else if("Charlestown".equals(commComboBox.getSelectedItem())){
            hosComboBox.setModel(charModel);
        } else if("Brooklyn".equals(commComboBox.getSelectedItem())){
            hosComboBox.setModel(broModel);
        } else if("Queens".equals(commComboBox.getSelectedItem())){
            hosComboBox.setModel(queModel);
        }
        */
    }//GEN-LAST:event_commComboBoxActionPerformed

    private void hosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosComboBoxActionPerformed
        // TODO add your handling code here:
        String hospitalName = (String) hosComboBox.getSelectedItem();

        DefaultComboBoxModel docModel = new DefaultComboBoxModel(requiredDoctor(hospitalName));
        docComboBox.setModel(docModel);

        /*if ("Mass Hospital".equals(hosComboBox.getSelectedItem())){
            docComboBox.setModel(masModel);
        } else if("Arbour Hospital".equals(hosComboBox.getSelectedItem())){
            docComboBox.setModel(arbModel);
        } else if("Boston Hospital".equals(hosComboBox.getSelectedItem())){
            docComboBox.setModel(boshosModel);
        } else if("Carney Hospital".equals(hosComboBox.getSelectedItem())){
            docComboBox.setModel(carModel);
        } else if ("Bellevue Hospital".equals(hosComboBox.getSelectedItem())){
            docComboBox.setModel(bellModel);
        } else if("Calvary Hospital".equals(hosComboBox.getSelectedItem())){
            docComboBox.setModel(calModel);
        } else if("Elmhurst Hospital".equals(hosComboBox.getSelectedItem())){
            docComboBox.setModel(elmModel);
        } else if("Brookdale Hospital".equals(hosComboBox.getSelectedItem())){
            docComboBox.setModel(brooModel);
        }
        */

    }//GEN-LAST:event_hosComboBoxActionPerformed

    private void docComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_docComboBoxActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        // TODO add your handling code here:
        boolean patientYN = false;

        lblPersonId.setText(String.valueOf(loggedinPerson.getPersonId()));

        patientYN = ifPatientExist(loggedinPerson.getPersonId());

        String docNameFull = (String)docComboBox.getSelectedItem();
        String docName = docNameFull.substring(0, docNameFull.indexOf(' '));
        Doctor doc = new Doctor();
        for(Doctor d: doctorDirectory.getDoctorList()){
            if(docName.equals(d.getDoctorFirstName())){
                doc = d;
                break;
            }
        }

        if(!patientYN){
            Patient patient = new Patient(loggedinPerson);
            patient.setPatientId(loggedinPerson.getPersonId());
            patient.setPatientDoctorId(doc.getDoctorId());
            patient.setPatientDoctorName((String) docComboBox.getSelectedItem());
            patient.setPatientHospitalName((String) hosComboBox.getSelectedItem());
            patientDirectory.addNewPatient(patient);
            System.out.println(patient.getPatientId());
            JOptionPane.showMessageDialog(this, "Appointment Confirmed ");
        }
        else{
            JOptionPane.showMessageDialog(this, "Appointment already confirmed");
        }

    }//GEN-LAST:event_bookBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        switchPanels(personViewOptionPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
        switchPanels(personViewOptionPanel);
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void appointmentTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appointmentTableKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_appointmentTableKeyReleased
private boolean userNameUnique(String username){
    
    boolean unique = false;
     
        for(Person p: personDirectory.getPersonList()){
            if(username.equals(p.getPersonUserName())){
               unique = false;
               break;
            }
            else{
                unique = true;
            }
        }

    return unique;
}

DefaultComboBoxModel nyModel = new DefaultComboBoxModel(new String[]{"Brooklyn", "Queens"});

DefaultComboBoxModel allModel = new DefaultComboBoxModel(new String[]{"Mass Hospital", "Arbour Hospital"});
DefaultComboBoxModel charModel = new DefaultComboBoxModel(new String[]{"Boston Hospital", "Carney Hospital"});
DefaultComboBoxModel broModel = new DefaultComboBoxModel(new String[]{"Bellevue Hospital", "Calvary Hospital"});
DefaultComboBoxModel queModel = new DefaultComboBoxModel(new String[]{"Elmhurst Hospital", "Brookdale Hospital"});

DefaultComboBoxModel masModel = new DefaultComboBoxModel(new String[]{"Ann Anand", "Carl Ugi"});
DefaultComboBoxModel arbModel = new DefaultComboBoxModel(new String[]{"Fran Hawkins", "Lenny Chan"});
DefaultComboBoxModel boshosModel = new DefaultComboBoxModel(new String[]{"Priti Pap", "Mukul Kellogg"});
DefaultComboBoxModel carModel = new DefaultComboBoxModel(new String[]{"Sunita Kumar", "Dev Janson"});
DefaultComboBoxModel bellModel = new DefaultComboBoxModel(new String[]{"John Solos", "Krista Fu"});
DefaultComboBoxModel calModel = new DefaultComboBoxModel(new String[]{"Faisal Carlson", "Nigel Tyr"});
DefaultComboBoxModel elmModel = new DefaultComboBoxModel(new String[]{"Elin Lim", "Michael Kale"});
DefaultComboBoxModel brooModel = new DefaultComboBoxModel(new String[]{"Sani Cherry", "Alison Merry"});

 /*DefaultComboBoxModel cityModel = new DefaultComboBoxModel(requiredCity());
        cityComboBox1.setModel(cityModel);*/

private String[] requiredCity(){
        
        String[] cityNames = new String[10];
        int i =0;
        
        for(City c: cityList){
        cityNames[i] = c.getCityName();
        i++;
        }
        
        return cityNames;
    }

private int getUniqueId() {
        
        int randomPIN = (int)(Math.random()*90000)+10000;
        for(Person person : personDirectory.getPersonList()){
            if(person.getPersonId()== randomPIN){
                getUniqueId();
            }
        }
        return randomPIN;
    }

    private boolean ifPatientExist(int id) {
        
        boolean exists = false;
        
        for(Patient patient : patientDirectory.getPatientList()){
            if(patient.getPatientId() == id){
            exists = true;
            }
        }
        return exists;
    }
    
    private void switchPanels(Component component) {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(component);
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();
    }
    
    private String[] requiredCommunity(String cityName){
        
        String[] communityNames = new String[10];
        int i =0;
        
        int cityId = 0;
        
        for(City c: cityList){
            if(c.getCityName().equals(cityName)){
                cityId = c.getCityId();
                break;
            }
        }
        
        for(Community c: communityDirectory.getCommunityList()){
            if(c.getCityID() == cityId){
                communityNames[i] = c.getCommunityAddress();
                i++;
            }
        }
        
        return communityNames;
    }
    
    private String[] requiredHospital(String communityName){
        
        String[] hospitalNames = new String[10];
        int i =0;
        
        int commId = 0;
        
        for(Community com: communityDirectory.getCommunityList()){
            if(com.getCommunityAddress().equals(communityName)){
                commId = com.getCommunityID();
                break;
            }
        }
        
        for(Hospital h: hospitalDirectory.getHospitalList()){
            if(h.getHospitalCommId() == commId){
                hospitalNames[i] = h.getHospitalName();
                i++;
            }
        }
        
        return hospitalNames;
    }
    
    private String[] requiredDoctor(String hospitalName){
        
        String[] doctorNames = new String[10];
        int i =0;
        
        int hosId = 0;
        
        for(Hospital hos: hospitalDirectory.getHospitalList()){
            if(hos.getHospitalName().equals(hospitalName)){
                hosId = hos.getHospitalId();
                break;
            }
        }
        
        for(Doctor doc: doctorDirectory.getDoctorList()){
            if(doc.getDoctorHosId() == hosId){
                doctorNames[i] = doc.getDoctorFirstName() + " " + doc.getDoctorLastName();
                i++;
            }
        }
        
        return doctorNames;
    }
    
    private String[] requiredHouse(String communityName){
        
        String[] houseNames = new String[10];
        int i =0;
        
        int commId = 0;
        
        for(Community com: communityDirectory.getCommunityList()){
            if(com.getCommunityAddress().equals(communityName)){
                commId = com.getCommunityID();
                break;
            }
        }
        
        for(House h: houseDirectory.getHouseList()){
            if(h.getHouseCommId() == commId){
              houseNames[i] = h.getHouseName();
              i++;
            }
        }
        
        return houseNames;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appointmentTable;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton backToLoginBtn;
    private javax.swing.JButton bookBtn;
    private javax.swing.JButton btnAddNewCity;
    private javax.swing.JButton btnAddNewComm;
    private javax.swing.JButton btnAddNewHouse;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox<String> chooseHouseBox;
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JComboBox<String> cityComboBox1;
    private javax.swing.JLabel cityLbl;
    private javax.swing.JComboBox<String> commComboBox;
    private javax.swing.JComboBox<String> commComboBox1;
    private javax.swing.JLabel commLbl;
    private javax.swing.JComboBox<String> docComboBox;
    private javax.swing.JLabel docLbl;
    private javax.swing.JButton encounterDetailsBtn;
    private javax.swing.JTable encounterTable;
    private javax.swing.JButton findDocBtn;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JLabel headingLbl1;
    private javax.swing.JLabel headingLbl2;
    private javax.swing.JLabel headingLbl3;
    private javax.swing.JComboBox<String> hosComboBox;
    private javax.swing.JLabel hosLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAge1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblComm;
    private javax.swing.JLabel lblFname;
    private javax.swing.JLabel lblHouseNo;
    private javax.swing.JLabel lblHouseNo1;
    private javax.swing.JLabel lblHouseNo2;
    private javax.swing.JLabel lblLname;
    private javax.swing.JLabel lblPersonId;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserName1;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblfname;
    private javax.swing.JLabel lbllname;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel personIdLbl;
    private javax.swing.JPanel personPanel;
    private javax.swing.JButton personRegisterBtn;
    private javax.swing.JPanel personViewOptionPanel;
    private javax.swing.JButton registerBtn;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPass;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtuserName;
    private javax.swing.JPanel viewEncounterPanel;
    // End of variables declaration//GEN-END:variables
}
